### ISSUE TITLE
Problems with user's rights management

### ISSUE THREAD

**Issue by gable44** [chiefonboarding/ChiefOnboarding#120]
Employees access level can not be changed to admin at People ->Employees
If an employee has already registered at People ->Employees the employees it can not be added at Settings -> Administrators.
(Also no errors were shown like this user with this email exists)

Admin access levels can not be changed at Settings -> Administrators (Limited access and Full Access)

**Comment by GDay** [comment]
Thanks for reporting this bug! I have confirmed this issue. It will be fixed in version 2 (scheduled to be released in a few weeks).
For now, you will have to delete the user and recreate it, though be aware that it might lead to some data loss (manager/buddy connections to new hires will be gone, the profile of the user will be gone, etc).

Alternatively, you could also register them again with adding a + sign in the email address. Like: `hello+new@chiefonboarding.com`, if you need to keep their old account around.

If you have server access, then you can "upgrade" the user without data loss. These are the options:
```
ROLE_CHOICES = (
    (0, 'New Hire'),
    (1, 'Admin'),
    (2, 'Manager'),
    (3, 'Other')
)
```

Changing a user's role would go like this:

```
python manage.py shell
from users.models import User
user = User.objects.get(email="emailfromuser")
user.role = 1
user.save()
```
Obviously, change the `1` to what type you want them to be and change the `emailfromuser` to an actual email address.

**Comment by GDay** [comment]
v2.0 is out and this has been fixed there! 

![image](https://user-images.githubusercontent.com/1939656/178082862-1d5dd3ac-1d71-4e9e-a92b-d3f6c236b749.png)
