### ISSUE TITLE
Error reading back/.env - if you're not configuring your environment separately, check this

### ISSUE THREAD

**Issue by Robert-Ernst** [chiefonboarding/ChiefOnboarding#88]
Probably heavily related to https://github.com/chiefonboarding/ChiefOnboarding/issues/77

The error message is:
```
chiefonboarding             | /usr/local/lib/python3.9/site-packages/environ/environ.py:637: UserWarning: Error reading back/.env - if you're not configuring your environment separately, check this.
```

My `.env` file shows this:
```
SECRET_KEY=secret1
POSTGRES_PASSWORD=secret2
```
and then I'm inserting the variables inside the `docker-compose.yml` via ${SECRET_KEY}

After reading Issue #77 and seeing the improvements here I still run into problems.
I did quite some changes on the docker-compose file to use the `.env` file to have the passwords not into the `docker-compose.yml` file itself.
I guess the error I am getting is somehow related using this `.env` file. 

Bonus question:
Why define the Docker network with the name global?

**Comment by GDay** [comment]
The error message you get, is actually just a warning. I do see why you got confused though. The warning message you get is from a package that we use in Django to set the secrets in the `settings.py` file. This warning will always be there, because we are using Docker, which will provide environment variables to Django. So there isn't a `.env` file that the package will read.

Though, you can provide an `.env` file to Docker if you want. Your approach should work too.

Did the application run, or did you actually run into some kind of error? (ignoring the warning that is mentioned in your post)
It should work fine with the approach that you are taking.

>Bonus question:
>Why define the Docker network with the name global?

Don't really have a reason for that. I could swap it out with something like `main` if you feel like that would be better. The `global` name never caused me any problems (with docker-compose).
