### ISSUE TITLE
Unable to set Appointments and Introductions to the new hiree's tasks list

### ISSUE THREAD

**Issue by omkardeekonda** [chiefonboarding/ChiefOnboarding#90]
We are trying to set up the tasks for the new hirees. We are currently stuck with Appointments and Introductions tasks.

Steps we are following:
1. Create an Appointment or Introduction from Templates menu.
2. Go to a new hiree's tasks tab.
3. Add an Appointment or Introdcution as a task.
4. Navigate to any other tab in new Hiree's page and return back to Tasks tab.
5. Appointment or Introduction added using step 3 are not visible.

**Comment by GDay** [comment]
Thanks for reporting this. I indeed confirmed the issue and I will get this fixed ASAP. I will update the ticket when I got this fixed.

**Comment by GDay** [comment]
I have pushed a fix for this. It has been deployed to both the `deploy` branch and also as a Docker image.

Please note though: the appointments aren't really implemented anywhere, I pretty much forgot about them. Kind of low priority at the moment because the date in these appointments would pass at some point, which makes it hard to keep reuse them. If you have a good use case for them, then let me know and I will reconsider. For now, you could just create a todo item instead of an appointment.

The introductions should work fine in both Slack and the web portal.
